### ISSUE TITLE
Form API documentation missing #config special property

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop-ops/docs.backdropcms.org#51] opened 2018-08-14 19:51 UTC
On the Form API documentation page, https://api.backdropcms.org/form_api, the `#config` property is missing. I first saw mention of it in https://api.backdropcms.org/converting-modules-from-drupal, and I like the fact that I don't have to manually save the values in a submit function if I don't want to. 

Shouldn't the `#config` property be listed on the Form API page? I'm just trying out using that way of saving config so I don't have much else to add at this point as far as the wording that property should have.

**Comment by BWPanda** [comment] 2019-09-28 03:51
Marking this as a duplicate of https://github.com/backdrop-ops/api.backdropcms.org/issues/66 as it should be fixed automatically when that issue is addressed.

**Comment by BWPanda** [comment] 2019-09-28 09:58
Sorry, won't be automatic. But easier to wait until https://github.com/backdrop-ops/api.backdropcms.org/issues/66 is done to add it.

**Comment by jenlampton** [comment] 2019-11-25 01:01
I've added #config:
https://api.backdropcms.org/form_api#config

**Closed by jenlampton** 2019-11-25 01:01 UTC
Labels: status - postponed
